swagger: '2.0'
info:
  description: 'backendTestV1 '
  version: 1.0.0
  title: backendTest
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: carlinhoaa@hotmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:3000'
basePath: /api/v1
tags:
  - name: operaciones
    description: Operaciones a realizar
schemes:
  - http
paths:
  /operations:
    post:
      tags:
        - operaciones
      summary: Obtener resultado de la operacion
      description: Envia parametros a calcular
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: numero1
          in: formData
          description: primer numero
          required: true
          type: string
        - name: operador
          in: formData
          description: tipo de operador
          required: true
          type: string
        - name: numero2
          in: formData
          description: segundo numero
          required: true
          type: string
      responses:
        '200':
          description: Succesfully calculated
          schema:
            $ref: '#/definitions/operation'
        '400':
          description: No se ha podido calcular
          schema:
            type: object
            properties:
              error:
                type: string
definitions:
  operation:
    type: object
    required:
      - numero1
      - operador
      - numero2
    properties:
      numero1:
        type: string
      operador:
        type: string
      numero2:
        type: string
      resultado:
        type: string
    xml:
      name: operation
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
